require Pod::Executable.execute_command(
  "node",
  [
    "-p",
    "require.resolve('react-native/scripts/react_native_pods.rb', { paths: [process.argv[1]] })",
    File.expand_path("../..", __dir__),
  ]
).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

react_native_path = "../../node_modules/react-native"
repository_root = File.expand_path("../..", __dir__)

target "BottomSheetNativeTestHost" do
  use_react_native!(
    :path => react_native_path,
    :app_path => repository_root,
    :config_file_dir => repository_root,
  )

  pod "ReactNativeBottomSheet", :path => "../.."

  target "BottomSheetNativeTests" do
    inherit! :search_paths
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    react_native_path,
    :mac_catalyst_enabled => false,
  )
end
